name: metamcp
services:
  - name: metamcp-app
    source_dir: /
    github:
      repo: metatool-ai/metamcp
      branch: main
    run_command: docker run -p 12008:12008 --env-file .env ghcr.io/metatool-ai/metamcp:latest
    environment_slug: docker
    instance_count: 1
    instance_size_slug: basic-xxs
    envs:
      - key: POSTGRES_HOST
        value: ${POSTGRES_HOST}
        scope: RUN_AND_BUILD_TIME
      - key: POSTGRES_PORT
        value: ${POSTGRES_PORT}
        scope: RUN_AND_BUILD_TIME
      - key: POSTGRES_USER
        value: ${POSTGRES_USER}
        scope: RUN_AND_BUILD_TIME
      - key: POSTGRES_PASSWORD
        value: ${POSTGRES_PASSWORD}
        scope: RUN_AND_BUILD_TIME
      - key: POSTGRES_DB
        value: ${POSTGRES_DB}
        scope: RUN_AND_BUILD_TIME
      - key: DATABASE_URL
        value: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
        scope: RUN_AND_BUILD_TIME
      - key: APP_URL
        value: ${APP_URL}
        scope: RUN_AND_BUILD_TIME
      - key: NEXT_PUBLIC_APP_URL
        value: ${APP_URL}
        scope: RUN_AND_BUILD_TIME
      - key: BETTER_AUTH_SECRET
        value: ${BETTER_AUTH_SECRET}
        scope: RUN_AND_BUILD_TIME
      - key: TRANSFORM_LOCALHOST_TO_DOCKER_INTERNAL
        value: ${TRANSFORM_LOCALHOST_TO_DOCKER_INTERNAL}
        scope: RUN_AND_BUILD_TIME
    ports:
      - 12008
    health_check:
      http_path: /health
      initial_delay_seconds: 30
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3

  - name: metamcp-postgres
    source_dir: /
    github:
      repo: metatool-ai/metamcp
      branch: main
    run_command: docker run -p 5432:5432 -e POSTGRES_DB=${POSTGRES_DB} -e POSTGRES_USER=${POSTGRES_USER} -e POSTGRES_PASSWORD=${POSTGRES_PASSWORD} postgres:16-alpine
    environment_slug: docker
    instance_count: 1
    instance_size_slug: basic-xxs
    envs:
      - key: POSTGRES_DB
        value: ${POSTGRES_DB}
        scope: RUN_AND_BUILD_TIME
      - key: POSTGRES_USER
        value: ${POSTGRES_USER}
        scope: RUN_AND_BUILD_TIME
      - key: POSTGRES_PASSWORD
        value: ${POSTGRES_PASSWORD}
        scope: RUN_AND_BUILD_TIME
    ports:
      - 5432
    health_check:
      http_path: /health
      initial_delay_seconds: 30
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3

databases:
  - name: metamcp-postgres
    engine: PG
    version: "16"
    production: false
    cluster_name: metamcp-postgres-cluster
    db_name: ${POSTGRES_DB}
    db_user: ${POSTGRES_USER}
    db_password: ${POSTGRES_PASSWORD}
